name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: bash install_dependencies.sh
    - name: make
      run: make
      env:
        BIRDEE_HOME: ./BirdeeHome
    - name: make tests
      run: make tests
